name: Build Docker Image
on: 
  push:
    tags:
      - '*'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Send start message to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          format: markdown
          message: |
            GitHub Actions Start
            Workflow Name: ${{ github.workflow }}
            Url: https://github.com/LemonNekoGH/reminder-bot
            Trigger: `${{ github.ref_name }}` `${{ github.event.commits[0].id }}`

  test:
    needs: start
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Golang environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Run test
        run: go test -race -coverprofile=coverage.out -covermode=atomic $(go list ./... | grep -v github.com/lemonnekogh/reminderbot/ent)

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Golang environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container 
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: version=${{ github.ref_name }}
          tags: 'ghcr.io/lemonnekogh/reminder-bot:latest, ghcr.io/lemonnekogh/reminder-bot:${{ github.ref_name }}'

  end:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Send start message to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          format: markdown
          message: |
            GitHub Actions Start
            Workflow Name: ${{ github.workflow }}
            Url: https://github.com/LemonNekoGH/reminder-bot
            Trigger: `${{ github.ref_name }}` `${{ github.event.commits[0].id }}`
