name: Pull Request Check
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint on pull request
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Golang environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: Verify ent generated files
        uses: ent/contrib/ci@master

  build-test:
    name: Build on pull request
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Golang environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Build
        run: go build ./cmd/reminderbot/main.go

  test:
    name: Test on pull request
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Golang environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Run test
        run: go test -race -coverprofile=coverage.out -covermode=atomic $(go list ./... | grep -v github.com/lemonnekogh/reminderbot/ent)

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
