name: Pull Request Check
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint on pull request
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Check BOM
        uses: arma-actions/bom-check@v1
      
      - name: Check for CRLF endings
        uses: erclu/check-crlf@v1

      - name: Setup dotnet environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Lint
        run: |
          dotnet tool install -g dotnet-format
          dotnet format -v diag 'ReminderBot.sln'

  test:
    name: Test on pull request
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup dotnet environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Run test
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
